GX3-2958 problemas con el repositorio, aparece error: Parsing error: …
upex-galaxy/upex-cypress-trello pull request #56
Opened 2024-04-12 18:01 UTC by JoseManuel1994

definiendo test y creando pakage.

aun no estan completos y les queda mucho trabajo.

siempre me aparece el error:  Parsing error: Cannot read file 'f:\upexgalaxyauto\upex-cypress-trello\tsconfig.eslint.json'.eslint al principio de cada archivo.

2024-04-12 19:50 UTC, JoseManuel1994 commented
Creado pakage con el objeto trello para reutilización de codigo y mayor legibilidad del código con funciones:
getLists() para obtener listas de tablero.
getCards() para obtener cards del tablero.
cardCountByList() para obtener el numero de cards por lista.
getTargetList() para seleccionar la primera lista con menor numero de cards.

falta por desarrollar Json para reutilización de datos y mayor legibilidad del código.
crear sanitytest.
y archivo md con descripción de la US

2024-04-16 16:34 UTC, ZwitterKaneda requested changes
Hmmm acá nos falta el .md de la documentación y el .yml del pipeline @JoseManuel1994

2024-04-16 20:21 UTC, JoseManuel1994 commented
Añadido archivo GX3-2958-trello-api-cards.json con información importante de los test.
Añadido funciones a GX3-2958_trello-api-cards.ts.
createCard() para crear tajetas.
getRandomList() selecciona un lista aleatoria de un tablero.
archiveCards() archiva todas la cards del tablero.
añadido GX3-2958.md con información de los test.
añadido sanity con información del sanity test.

2024-04-24 12:54 UTC, ZwitterKaneda approved these changes

2024-04-24 12:55 UTC, ZwitterKaneda commented
Buen trabajo @JoseManuel1994 si quieres agregar nuevas funcionalidades, tienes que hacerme el PR una vez terminado :3

2024-04-24 12:55 UTC, merged